---
- hosts: localhost
  become: no
  gather_facts: yes

  vars_files:
    - ../../lambda/infra/vars/lambda.yml

  vars:
    - dist_dir: "{{ playbook_dir }}/../dist"
    - app_code_dir: "go-server"

  tasks:
    - name: Ensure dist directory is clean before we start
      file:
        path: "{{ dist_dir }}"
        state: absent

    - name: Make dist directory
      file:
        path: "{{ dist_dir }}"
        state: directory

    - name: Set full path to tar ball
      set_fact:
        deploy_package_filename: "{{ dist_dir }}/{{ app_code_dir }}.tar"

    - name: Create the tar ball
      command: "tar -cvf {{ deploy_package_filename }} -C {{ playbook_dir }}/../{{ app_code_dir }}/ ."

    - name: Copy tarball to s3
      command: "aws s3 cp {{ deploy_package_filename }} {{ code_bucket_name }}/rpi/{{ ansible_date_time.iso8601 }}/{{ app_code_dir }}.tar"


- hosts: raspberries
  become: yes

  vars:
    - bundle_name: "{{ hostvars['localhost']['app_code_dir'] }}"
    - bundle_local_path: "{{ hostvars['localhost']['dist_dir'] }}/{{ bundle_name }}"
    - bundle_remote_path: '/opt'

  tasks:
    - name: Copy tar ball to RPi
      copy:
        src: "{{ bundle_local_path }}"
        dest: "{{ bundle_remote_path }}/{{ bundle_name }}"

    # - name:
