---
- hosts: localhost
  gather_facts: no

  vars_files:
    - vars/lambda.yml

  tasks:

    - name: create lambda stack
      cloudformation:
        state: present
        stack_name: "{{ lambda_stack_name }}"
        region: "{{ region }}"
        template: "cfn/lambda-stack.yml.cform"
        template_parameters:
          DataStackName: "{{ data_stack_name }}"
          FunctionName: "{{ base_stack_name }}_lambda_function"
          PackagePath: "{{ code_path_base }}/index.zip"
        tags:
          Stack: "{{ lambda_stack_name }}"