---
- hosts: localhost
  gather_facts: no

  vars_files:
    - vars/lambda.yml
    - vars/config.yml

  tasks:

    - name: create lambda stack
      cloudformation:
        state: present
        stack_name: "{{ lambda_stack_name }}"
        region: "{{ region }}"
        template: "cfn/lambda-stack.yml.cform"
        template_parameters:
          DataStackName: "{{ data_stack_name }}"
          FunctionName: "{{ base_stack_name }}_lambda_function"
          PackagePath: "{{ code_path }}"
          AlexaApplicationId: "{{ alexa_application_id }}"
          SparkabowlAccessKey: "{{ sparkabowl_access_key }}"
            SparkabowlSecretKey: "{{ sparkabowl_secret_key }}"
        tags:
          Stack: "{{ lambda_stack_name }}"