---
- hosts: localhost
  gather_facts: no

  vars_files:
    - vars/lambda.yml
    - vars/config.yml
    - vars/access-key.yml
    - vars/config-stack-vars.yml

  tasks:

    - name: create lambda stack
      cloudformation:
        state: present
        stack_name: "{{ lambda_stack_name }}"
        region: "{{ region }}"
        template: "cfn/lambda-stack.yml.cform"
        template_parameters:
          DataStackName: "{{ data_stack_name }}"
          ConfigStackName: "{{ config_stack_name }}"
          ConfigFilePath: "{{ config_file_path }}"
          FunctionName: "{{ lambda_function_name }}"
          PackagePath: "{{ code_path }}"
          AlexaApplicationId: "{{ alexa_application_id }}"
          SparkabowlAccessKey: "{{ sparkabowl_access_key }}"
        tags:
          Stack: "{{ lambda_stack_name }}"