---
- name: destroy virtualenv
  file:
    path: "{{ venv_path }}"
    state: absent

- name: make virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ venv_path }}"
    virtualenv_command: virtualenv
    virtualenv_python: python2.7
  with_items:
    - requests
    - boto3
    - chalice
    - cryptography
    - mock