---
- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    - infra/vars/lambda.yml

  tasks:
    - command: "./build-deploy-bundle.sh {{ bundle_name }}"
    - command: "aws s3 cp build/{{ bundle_name }} s3://{{ code_bucket_name }}/{{ code_path }}"